
def additoin(x, y):
    x = 10
    y = 20
    print("Addition:", x + b)

# additoin(10, 20)


try:
    additoin(10 , 20)
    print("the operation is successful")
except NameError:
    print("Please try a valid value ")
